
const PAGE_TEXT = {
  th: {
    siteName: "แนะนำสถานที่ท่องเที่ยวร้านค้าและสินค้า",
    placesNav: "สถานที่",
    favoritesNav: "รายการโปรด",
    signIn: "เข้าสู่ระบบ",
    signUp: "สมัครสมาชิก",
    signOut: "ออกจากระบบ",

    homeKicker: "EXPLORE THAILAND",
    homeTitle: "ค้นหาสถานที่<br>ร้านค้า และสินค้า",
    homeAccent: "ทั่วประเทศไทย",
    homeDescription: "ค้นหาสถานที่ท่องเที่ยว ร้านค้า และสินค้า เลือกตามภาค จังหวัด และหมวดหมู่ พร้อมดูรายละเอียดได้โดยไม่จำเป็นต้องเข้าสู่ระบบ",
    searchPlaceholder: "ค้นหาชื่อสถานที่ จังหวัด หรือหมวดหมู่...",
    searchButton: "ค้นหา",

    recommendedTitle: "สถานที่แนะนำ",
    recommendedSub: "สถานที่น่าสนใจที่เราอยากแนะนำให้คุณ",
    viewAll: "ดูสถานที่ทั้งหมด",

    chooseRegion: "เลือกภาค",
    chooseRegionSub: "เลือกภาคและจังหวัดเพื่อดูสถานที่ที่สนใจ",
    chooseProvince: "เลือกจังหวัด",
    placeTitle: "สถานที่",
    placeSub: "รายละเอียดสถานที่สามารถดูได้โดยไม่ต้องเข้าสู่ระบบ",

    categoryAll: "ทั้งหมด",
    categoryNature: "ธรรมชาติ",
    categoryHistory: "ประวัติศาสตร์",
    categoryActivity: "ที่เที่ยว & กิจกรรม",
    categoryReviews: "รีวิว",
    categoryNearMe: "ใกล้ฉัน",
    nearMeLoading: "กำลังค้นหาสถานที่ใกล้คุณ...",
    nearMePermission: "กรุณาอนุญาตการเข้าถึงตำแหน่งเพื่อใช้เมนูใกล้ฉัน",
    nearMeUnavailable: "เบราว์เซอร์นี้ไม่รองรับการค้นหาตำแหน่ง",
    distanceLabel: "ห่างจากคุณ",
    reviewCountLabel: "รีวิว",
    searchSuggestionTitle: "สถานที่ที่พบ",

    noData: "ยังไม่มีข้อมูลในส่วนนี้",
    noDataSub: "สามารถเพิ่มข้อมูลใหม่ได้ที่ data.js",
    noFavorites: "ยังไม่มีรายการโปรด",
    noFavoritesSub: "กด ♡ บนสถานที่ที่ชอบเพื่อบันทึกไว้",

    address: "ที่อยู่",
    hours: "เวลา",
    phone: "โทร",
    rating: "คะแนน",
    map: "เปิด Google Maps",

    favoritesTitle: "รายการโปรด",
    favoritesSub: "สถานที่ที่คุณบันทึกไว้",

    authTitleSignIn: "เข้าสู่ระบบ",
    authTitleSignUp: "สร้างบัญชีใหม่",
    authSubtitleSignIn: "เข้าสู่ระบบเพื่อบันทึกรายการโปรดของคุณ",
    authSubtitleSignUp: "สมัครสมาชิกเพื่อใช้งานรายการโปรด",
    google: "ดำเนินการต่อด้วย Google",
    facebook: "ดำเนินการต่อด้วย Facebook",
    or: "หรือ",
    username: "Username",
    password: "Password",
    confirmPassword: "ยืนยัน Password",
    signInButton: "เข้าสู่ระบบ",
    signUpButton: "สร้างบัญชี",
    demoNotice: "Username/Password ใช้งานได้ในโหมด Demo ส่วน Google และ Facebook ต้องตั้งค่า Firebase/OAuth ก่อนใช้งานจริง",
    usernameTooShort: "Username ต้องมีอย่างน้อย 3 ตัวอักษร",
    passwordTooShort: "Password ต้องมีอย่างน้อย 6 ตัวอักษร",
    usernameExists: "Username นี้ถูกใช้งานแล้ว",
    invalidLogin: "Username หรือ Password ไม่ถูกต้อง",
    passwordMismatch: "Password และยืนยัน Password ไม่ตรงกัน",
    socialNotConfigured: "ยังไม่ได้ตั้งค่า Firebase/OAuth สำหรับช่องทางนี้",
    loginToFavorite: "กรุณาเข้าสู่ระบบก่อนเพิ่มรายการโปรด"
  },

  en: {
    siteName: "Travel, Shop & Product Recommendations",
    placesNav: "Places",
    favoritesNav: "Favorites",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",

    homeKicker: "EXPLORE THAILAND",
    homeTitle: "Discover Places,<br>Shops & Products",
    homeAccent: "Across Thailand",
    homeDescription: "Explore destinations, shops, and products by region, province, and category. Place details remain available without signing in.",
    searchPlaceholder: "Search place, province, or category...",
    searchButton: "Search",

    recommendedTitle: "Recommended Places",
    recommendedSub: "Interesting places we recommend for your next trip.",
    viewAll: "View all places",

    chooseRegion: "Choose Region",
    chooseRegionSub: "Choose a region and province to explore.",
    chooseProvince: "Choose Province",
    placeTitle: "Places",
    placeSub: "Place details are available without signing in.",

    categoryAll: "All",
    categoryNature: "Nature",
    categoryHistory: "History",
    categoryActivity: "Attractions & Activities",
    categoryReviews: "Reviews",
    categoryNearMe: "Near Me",
    nearMeLoading: "Finding places near you...",
    nearMePermission: "Please allow location access to use Near Me.",
    nearMeUnavailable: "Location is not supported by this browser.",
    distanceLabel: "from you",
    reviewCountLabel: "reviews",
    searchSuggestionTitle: "Matching places",

    noData: "No data available yet.",
    noDataSub: "Add new data in data.js",
    noFavorites: "No favorites yet.",
    noFavoritesSub: "Tap ♡ on a place to save it.",

    address: "Address",
    hours: "Hours",
    phone: "Phone",
    rating: "Rating",
    map: "Open Google Maps",

    favoritesTitle: "Favorites",
    favoritesSub: "Places saved to your account.",

    authTitleSignIn: "Sign in",
    authTitleSignUp: "Create an account",
    authSubtitleSignIn: "Sign in to save your favorite places.",
    authSubtitleSignUp: "Create an account to use favorites.",
    google: "Continue with Google",
    facebook: "Continue with Facebook",
    or: "or",
    username: "Username",
    password: "Password",
    confirmPassword: "Confirm password",
    signInButton: "Sign in",
    signUpButton: "Create account",
    demoNotice: "Username/password works as a local demo. Google and Facebook require Firebase/OAuth configuration.",
    usernameTooShort: "Username must contain at least 3 characters.",
    passwordTooShort: "Password must contain at least 6 characters.",
    usernameExists: "This username is already in use.",
    invalidLogin: "Incorrect username or password.",
    passwordMismatch: "Passwords do not match.",
    socialNotConfigured: "Firebase/OAuth has not been configured for this provider.",
    loginToFavorite: "Please sign in before adding favorites."
  }
};
